Adde getSalesEvolution method in stats module
jsmrcaga/payutc.js pull request #2
Opened 2018-11-23 10:32 UTC by cesar-richard

2018-11-23 10:40 UTC, jsmrcaga requested changes
⚠️Ton éditeur met des tabs a t:2 et du coup ya tout qui a changé :P

2018-11-26 14:27 UTC, cesar-richard commented
Habile, c'est mon linter qui a fait ca. Tu veux que je le passe à combien, T:4 ?

2018-11-26 15:29 UTC, jsmrcaga approved these changes

2018-11-26 15:30 UTC, jsmrcaga commented
@cesar-richard jai approve, il faut juste que tu rebases sur master j'ai limpression et on est good to go

2019-03-08 09:26 UTC, cesar-richard commented
Euh on en était ou sur ca @jsmrcaga  ?

2019-03-08 11:55 UTC, jsmrcaga commented
C'est quoi `isAsync` déja ? il utilise le keyword `async` du coup il risque de péter sur node/des nouveaux navigateurs

2025-01-19 23:50 UTC, closed without merging